# Generated by Django 5.1.5 on 2025-06-04 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do autor', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da categoria', max_length=200)),
                ('description', models.TextField(help_text='Descrição da categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do livro', max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Preço do livro', max_digits=14, validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(999999999999.0)])),
                ('cover', models.URLField()),
                ('isHighlight', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('author', models.ManyToManyField(help_text='Autor do livro', to='product.author')),
                ('category', models.ManyToManyField(help_text='Categoria do livro', to='product.category')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='category',
            field=models.ManyToManyField(help_text='Categoria de livros do autor', to='product.category'),
        ),
    ]
